### ISSUE TITLE
Not an IETF draft (yet)

### ISSUE THREAD

**Issue by martinthomson** [francoismichel/ssh3#132]
The tagline on the repo says:

> SSH3: faster and rich secure shell using HTTP/3, checkout our article here: https://arxiv.org/abs/2312.08396 and the IETF draft: https://datatracker.ietf.org/doc/draft-michel-ssh3/

To be precise, this is François and Olivier draft.  It will be discussed at the IETF (which I'm very happy to see), but it is not great to imply that it is the product of the IETF.

**Comment by francoismichel** [comment]
Oops, sorry for the imprecision, I changed

> IETF draft

to

> Internet-Draft

I think [Internet-Draft](https://www.ietf.org/how/ids/) is the exact term we're looking for.

"draft design document" could also work if we are worried of some people inferring that it is the output of an IETF wg.
