### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by metaip** [francoismichel/ssh3#62]
Installed the program from source.
Go version go1.21.4 linux/amd64

Run:
**panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.mainWithStatusCode()
        /install/ssh3-0.1.0/ssh3/cli/client/main.go:281 +0x65de
main.main()
        /install/ssh3-0.1.0/ssh3/cli/client/main.go:1055 +0x13**

**Comment by francoismichel** [comment]
I think you should run the [latest available version](https://github.com/francoismichel/ssh3/releases/tag/v0.1.4)

It also seems you ran the `ssh3` command with no argument. You need to specify a host to connect to, like this example in the README:

    ssh3 -privkey ~/.ssh/id_rsa username@my-server.example.org/my-secret-path

But thank you for the issue, a readable error message or dusplaying the usage would be a lot more insightful than a panic, let's fix that.

**Comment by metaip** [comment]
Thank you guys!
