### ISSUE TITLE
BUG: Insufficient locking in cmd/ssh3-server

### ISSUE THREAD

**Issue by Yawning** [francoismichel/ssh3#80]
`Server.conversationHandler` is [called from the HTTP3 server's handler in a per-connection go routine](https://github.com/francoismichel/ssh3/blob/b880c1ec442f54a66dedabf00e51ecc50ea09bb1/server.go#L183C17-L183C36).

The handler in `cmd/ssh3-server`, [mutates](https://github.com/francoismichel/ssh3/blob/b880c1ec442f54a66dedabf00e51ecc50ea09bb1/cmd/ssh3-server/main.go#L786) [global state](https://github.com/francoismichel/ssh3/blob/b880c1ec442f54a66dedabf00e51ecc50ea09bb1/cmd/ssh3-server/main.go#L101).

Golang maps require synchronization for [concurrent writes and/or concurrent reads + writes](https://go.dev/doc/faq#atomic_maps).  The server appears to do both.

**Comment by francoismichel** [comment]
Thanks for the feedback ! I'll have a serious look at it after holidays. :-)
